### ISSUE TITLE
Préselectionner la date d'aujourd'hui

### ISSUE THREAD

**Issue by SebCorbin** [mabhub/makina-presences#24]

**Comment by mabhub** [comment]
J'ai fais une première modification pour que, lorsqu'aucune date n'est présente en `localStorage`, *aujourd'hui* soit utilisé par défaut. Cela permet déjà, à la première connexion à l'outil, d'avoir forcement un jour de sélectionné.
Reste encore à gérer le cas où la date en `localStorage` est un jour des semaines passées.

@SebCorbin dans ce que tu imagines, est-ce que "chaque fois qu'on charge l'outil", la date sélectionnée devrait être réinitialisé pour correspondre à aujourd'hui ? *(Ou bien si c'est "après-demain" qui est sélectionné, et qu'on recharge l'outil, on laisse la sélection sur ce jour là ?)*

**Comment by SebCorbin** [comment]
> @SebCorbin dans ce que tu imagines, est-ce que "chaque fois qu'on charge l'outil", la date sélectionnée devrait être réinitialisé pour correspondre à aujourd'hui ? (Ou bien si c'est "après-demain" qui est sélectionné, et qu'on recharge l'outil, on laisse la sélection sur ce jour là ?)

Pour moi au chargement c'est la date du jour qui devrait être affichée : c'est simple, on s'y attend, et de toute façon explicite puisque tu as un retour visuel vert sur le jour en question.

**Comment by pacproduct** [comment]
Je pense qu'il y a un effet de bord indésirable à ce changement, car maintenant, si la date du local storage n'est pas la date du jour, la première sélection de la date du jour n'a pas d'effet, surement parce que l'appli pense qu'on est déjà sur cette date ?
(La sélection de toute autre date fonctionne)

Illustration :

https://user-images.githubusercontent.com/2098407/143203383-c602eb74-ae21-4326-8a13-9be4b6c3432f.mp4

**Comment by mabhub** [comment]
Effectivement, le comportement actuel est problématique, surtout depuis 8ce189eedf9bf28fd2ea39c9933a25516a8be04c

À faire donc : 
- Mettre en place un *state* partagé *(via `useContext` peut-être ?)* au lieu de `use-persisted-state` pour propager la valeur du jour "actif" *(dans ̀Plan` et `PresenceCalendar`)*.
