### ISSUE TITLE
[UX] Position des boutons + et -

### ISSUE THREAD

**Issue by numahell** [mabhub/makina-presences#26]
Suggestion pour le placement des boutons + et - (vraiment qu'une suggestion)

- mettre le + à la suite des trigrammes
    ![image](https://user-images.githubusercontent.com/546686/142865914-24815788-2538-46c0-b457-e3509c888d74.png)

- mettre le - à l'intérieur du trigramme, comme pour les labels
    ![image](https://user-images.githubusercontent.com/546686/142866472-63d4befe-2f58-4fd9-9e1e-9e713732a858.png)

**Comment by mabhub** [comment]
Tel que les fonctions du hook `usePresences` sont implémentées pour le moment, placer le bouton ➖ à cet endroit impliquerait probablement un nombre excessif de _render_ de composants supplémentaire *(un par trigramme affiché dans le calendrier)*.

Donc je ne pense pas que ce changement soit *viable* tout de suite. Par contre, si on arrive à améliorer la gestion des fonctions de lecture/écriture des présences, pourquoi pas !
