### ISSUE TITLE
Duplications possibles des trigrammes

### ISSUE THREAD

**Issue by pacproduct** [mabhub/makina-presences#28]
En jouant avec la casse, il est possible de faire apparaître son trigramme plusieurs fois.

Comment reproduire le problème :
- S'identifier en tant que "abc", et s'inscrire sur un poste. "abc" apparaît dorénavant sur ce poste.
- S'identifier en tant que "ABC" : il est possible de s'inscrire sur un autre poste sans que la première occurrence ne soit retirée. De plus, comme les trigrammes sont forcés en minuscules à l'affichage, on ne voit pas de différence entre les 2 occurrences (sauf dans le menu de login en haut à droite) :
  ![image](https://user-images.githubusercontent.com/2098407/142868603-ee66472e-fb38-41a5-8a21-444013a4f7d5.png)

**Comment by pacproduct** [comment]
Note : en fait en se loggant avec "ABC", on peut s'inscrire sur autant de postes que l'on veut.

**Comment by mabhub** [comment]
C'est corrigé ! 🙂
