### ISSUE TITLE
Le déplacement de la map déclenche quand même l'inscription à une place

### ISSUE THREAD

**Issue by pacproduct** [mabhub/makina-presences#31]
Lorsqu'on maintient le clic de souris sur la carte, cela permet de déplacer le plan :+1:

Mais si cette action est démarrée en cliquant sur une place réservable par mégarde, une fois le déplacement terminé au relâchement de la souris, la dite place se fait réserver involontairement.

----

https://user-images.githubusercontent.com/2098407/143200614-39bf5b23-e741-4688-a629-cdbc6bf55f9d.mp4

**Comment by mabhub** [comment]
Bien vu ! 👍 🙏

A priori ce phénomène pourrait être évité en ajustant un paramètre de la configuration du module `react-zoom-pan-pinch` comme `panning.excluded`et/ou `pinch.excluded`.
