### ISSUE TITLE
Texte énorme sur le poste F1

### ISSUE THREAD

**Issue by pacproduct** [mabhub/makina-presences#33]
Très curieux, au survol du poste F1, l'un des textes de la popin est tout bonnement de taille colossale :
![image](https://user-images.githubusercontent.com/2098407/162152927-7f449884-cb5a-4d65-bb95-05abb5daf4d9.png)

**Comment by mabhub** [comment]
C'est corrigé !

----

**Explication :**

C'est un *simple problème* de contribution.
Dans les données, le contenu de la popin est en Markdown.

La plupart des contenus commencent ainsi :
```md
Poste équipé ouvert à tous

---

**Équipement** :  
```

Le `---` est ici une ligne de séparation *(`<hr />`)*.
Par contre, si le "double" retour a la ligne et remplacé par une simple retour à la ligne, le `---` est alors [interprété comme une formatage de titre](https://daringfireball.net/projects/markdown/syntax#header) de niveau 2 (syntaxe "Setext") :

```md
Poste équipé ouvert à tous
---

**Équipement** :  
```
