### ISSUE TITLE
2 semaines, c'est pas assez

### ISSUE THREAD

**Issue by pounard** [mabhub/makina-presences#37]
Très concrètement:

1. je le remplis consciencieusement,
2. et puis deux semaines passent,
3. quelqu'un nous rappelle à l'ordre et nous demande de le remplir une semaine après,
4. retour à l'étape 1

Voilà, c'est à dire qu'en fait, mes jours de présence *ne changent pas*. Et du coup, je ne suis pas inscrit une semaine sur trois.

Certains diront que c'est de la mauvaise volonté, et moi je réponds, peut être, mais très pragmatiquement ça va continuer comme ça pour toujours on si ne nous permet pas de nous inscrire plus longtemps à l'avance.

Trop d'outillage tue l'outillage, à un moment il faut être rationnel et faciliter la vie des utilisateurs.

**Comment by Gagaro** [comment]
Et si on allonge, pouvoir se positionner sur toutes les semaines suivantes d'un coup ? (je me pose le lundi, je peux faire tous les lundi suivant en même temps d'un coup).
